### ISSUE TITLE
BUG: ValueError when binning empty multiindex Dataframe

### ISSUE THREAD

**Issue by rob-tay** [FAST-HEP/fast-carpenter#51]
Binning a multi-index dataframe where no events pass a selection results in a ValueError. 

Seems to be an internal pandas bug and related to https://github.com/pandas-dev/pandas/pull/26112 (which has a merged fix but only tested when grouping by one column)

Can be reproduced with:

```
df = pd.DataFrame(dict(a=[0,1,2,4], b=[0, 0, 1, 1]))
df['a_bin'] = pd.cut(df.query('a > 5').eval('a', engine='numexpr'), [0, 1, 2], right=False)
df['b_bin'] = pd.cut(df.query('a > 5').eval('b', engine='numexpr'), [0, 1, 2], right=False)
df.groupby(['a_bin', 'b_bin']).size()
```
which produces,
`ValueError: Length of passed values is 4, index implies 0`

Here's the traceback when running fast-carpenter:
```
Traceback (most recent call last):
  File "/global/homes/r/rtaylor/.conda/envs/rabit-dev/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/global/homes/r/rtaylor/.conda/envs/rabit-dev/lib/python3.6/site-packages/mantichora/worker.py", line 27, in run
    self._run_tasks()
  File "/global/homes/r/rtaylor/.conda/envs/rabit-dev/lib/python3.6/site-packages/mantichora/worker.py", line 47, in _run_tasks
    result = task_func()
  File "/global/homes/r/rtaylor/.conda/envs/rabit-dev/lib/python3.6/site-packages/mantichora/main.py", line 18, in __call__
    return self.task(*self.args, **self.kwargs)
  File "/global/homes/r/rtaylor/.conda/envs/rabit-dev/lib/python3.6/site-packages/alphatwirl/concurrently/CommunicationChannel.py", line 16, in __call__
    return self.task(*self.args, **self.kwargs)
  File "/global/homes/r/rtaylor/.conda/envs/rabit-dev/lib/python3.6/site-packages/alphatwirl/loop/EventLoop.py", line 45, in __call__
    self.reader.event(event)
  File "/global/homes/r/rtaylor/.conda/envs/rabit-dev/lib/python3.6/site-packages/alphatwirl/loop/ReaderComposite.py", line 43, in event
    if reader.event(event) is False:
  File "/global/u1/r/rtaylor/RaBiT/sim/fast-carpenter/fast_carpenter/summary/binned_dataframe.py", line 175, in event
    out_dimensions=self._out_bin_dims)
  File "/global/u1/r/rtaylor/RaBiT/sim/fast-carpenter/fast_carpenter/summary/binned_dataframe.py", line 221, in _bin_values
    counts = bins.size()
  File "/global/homes/r/rtaylor/.conda/envs/rabit-dev/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 1227, in size
    result = self.grouper.size()
  File "/global/homes/r/rtaylor/.conda/envs/rabit-dev/lib/python3.6/site-packages/pandas/core/groupby/ops.py", line 233, in size
    dtype='int64')
  File "/global/homes/r/rtaylor/.conda/envs/rabit-dev/lib/python3.6/site-packages/pandas/core/series.py", line 249, in __init__
    .format(val=len(data), ind=len(index)))
ValueError: Length of passed values is 1, index implies 0
```

**Comment by benkrikler** [comment]
Sorry, @rob-tay, I'm not getting time to tackle this, do you think you'll get a chance to add in a safe-guard to the binned-dataframe stage to protect against this problem?

**Comment by benkrikler** [comment]
Looking at the pandas issue you mention, Rob, the fix will only become available through 0.25.0 which is not yet available via pypi / conda (only as a pre-release).  Did you test with 0.25.0 at all, or just 0.24.2?  Your test code above seems to work ok for that version for me.

**Comment by benkrikler** [comment]
Hi @rob-tay PR #60 might have addressed some of this issue and I see that the latest version of pandas on pypi is v0.25.0 which should contain the fixes we need.  Are you able to test things to see if we can close this?

**Comment by benkrikler** [comment]
I've tried this out with the latest fast-carpenter (v0.13.4) and this seems to be fine so I'm closing this off.
